
trigger:
- master

pool:
  vmImage: ubuntu-latest
variables:
  - group: sonarcloud
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Build App'

- script: |    
    npm run test
  displayName: 'Unit test'

- script: |
    chmod +x sonar.sh & ./sonar.sh 0
    npm run sonar
  displayName: 'Code Analisys'
